// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zlzgmosgdnasvhcircso.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpsemdtb3NnZG5hc3ZoY2lyY3NvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4ODIzOTEsImV4cCI6MjA2NjQ1ODM5MX0.Ua32dJOpFykkcTJGbeIuC779Y_IO6vm7Uw6CzoaA2Ns";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);